
#############
### SETUP ###
#############

suppressMessages(library(tidyverse))
suppressMessages(library(purrr))

# Get all folders generated by samba.sh 
projects_folder <- commandArgs(trailingOnly = TRUE)[1]
projects_folder <- gsub(pattern = "/$", replacement = "", x = projects_folder) # remove final '/'
all_sub_folders <- list.dirs(path = projects_folder, full.names = TRUE)

dada2_folders <- all_sub_folders[grepl(x = all_sub_folders, pattern = "/01.dada2")]

output_folders <- all_sub_folders[grepl(x = all_sub_folders, pattern = "/outputs")]

###############
## FUNCTIONS ##
###############

log <- function(path){
    cat(paste("Analysing:", path, "\n"))
}

is_empty_folder <- function(path){
    # Check if a folder is empty or not
    file_names <- list.files(path, include.dirs = FALSE)
    ifelse(length(file_names) == 0, yes = TRUE, no = FALSE)
}

pick_correct_track_reads_file <- function(path){
    # PROBLEM:  Some PE sequenced projects are reanalysed as SE.
    # SOLUTION: Scan the files generated by analyse_project.sh
    #           to determine what track read file has to be joined
    #		for the consolidated file.

    # Check if PE and SE track reads file exists for a given project
    PE_track_reads <- paste0(path, "/track_reads_through_pipeline.tsv")
    PE_exists <- file.exists(PE_track_reads)

    SE_track_reads <- paste0(path, "/SE_track_reads_through_pipeline.tsv")
    SE_exists <- file.exists(SE_track_reads)

    # If no file was found:
    if( !PE_exists && !SE_exists ) {
        #cat(paste0("No track reads file for: ", bioproject))
	correct_track_file <- NA
    }

    # If PE and SE generated track_reads, project was
    # reanalysed as SE. Use that file then
    if( PE_exists && SE_exists ){
        correct_track_file <- SE_track_reads

    } else if( PE_exists && !SE_exists ) {
	# if only PE exists, use that
	correct_track_file <- PE_track_reads

    } else if ( !PE_exists && SE_exists ){
	# if only SE exists, use that
	correct_track_file <- SE_track_reads
    }
    # return
    correct_track_file
}

read_and_harmonise <- function(path){
    # PROBLEM:  track read through pipeline files of projects
    #           sequenced as PE have 2 extra column 
    #	        (denoisedR and merged).
    # SOLUTION: add that column of NAs to projects sequenced
    #           as SE.
    log(path)
    data <- read.delim(path)

    # if project is SE
    if( grepl(x = path, pattern = "SE_") ){
	# add missing columns
	data$denoisedR <- NA
	data$merged <- NA
	# reorder columns
	ordered_cols <- c("input", "filtered", "denoisedF", "denoisedR", "merged", "nochim")
        data <- data[, ordered_cols]

        # add column with the layout finally used in the analysis
	# as some PE projects might have end up as SE if they failed the QC
	data$library_layout <- "SINGLE"

    } else {
	# add column with the layout finally used in the analysis
	data$library_layout <- "PAIRED"
    }
    # return
    data
}

##############
#### MAIN ####
##############

# get projects with final output (i.e., were successfully analysed)
empty_output_folders <- sapply(output_folders, is_empty_folder)
dada2_folders <- dada2_folders[!empty_output_folders]

# list files that can be joined
track_reads_files_to_join <- sapply(dada2_folders, pick_correct_track_reads_file)

# join them
consolidated_df <- map(.x = track_reads_files_to_join,
		       .f = read_and_harmonise) %>%
    list_rbind() %>%
    rownames_to_column("run_accession")

# export final consolidated file
write_tsv(x = consolidated_df,
	  file = paste0(projects_folder, "/consolidated/track_reads.tsv"))
